name: Periodic update and publish

on:
  schedule:
    # Every day at 10:00, 18:00, 23:00 UTC
    - cron: "0 10,18,23 * * *"

jobs:
  update-and-deploy:
    name: Update and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install

      - name: Update and publish
        run: yarn run ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
